site_name: 我的仓库
site_url: https://colick-cgc.github.io/skills-github-pages/
nav:
  - 首页: index.md
  - 第一部分:
      - Part1/index.md
      - 随机文本: Part1/随笔.md
  - 第二部分:
      - Part2/index.md
  - 第三部分:
      - Part3/index.md
docs_dir: docs/

theme:
  name: material
  features:
    - navigation.tabs
    - search.suggest
    - search.highlight
    - search.share
    - navigation.top
    - navigation.indexes
