site_name: Karma的站
site_url: https://colick-cgc.github.io/skills-github-pages/
nav:
  - 首页: index.md
  - 文学:
      - Part1/index.md
      - 随机文本: Part1/随笔.md
  - 历史:
      - Part2/index.md
  - 数学:
      - Part3/index.md
docs_dir: docs/

theme:
  name: material
  features:
    - navigation.tabs
    - search.suggest
    - search.highlight
    - search.share
    - navigation.top
    - navigation.indexes
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
extra_css:
  - stylesheets/extra.css
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Colick-cgc
    - icon: fontawesome/solid/paper-plane
      link: mailto:chen3242022@63.com
copyright: Copyright &copy; 2024 - 2025 Karma
